# Ansible
# ansible_user: root


# Container runtimes ('containerd', 'docker')
container_runtime: docker

# Dokcer engine version
# containerd_version: 1.6.31

# A list of insecure registries you might need to define
# containerd_registry_mirrors: "https://docker.m.daocloud.io"
# containerd_dns: "8.8.8.8"
# containerd_default_runtime:

# Dokcer engine version
docker_version: 24.0.7

# A list of insecure registries you might need to define
# docker_data_root: /var/lib/docker
docker_registry_mirrors: "https://docker.m.daocloud.io"
docker_dns: "8.8.8.8"
docker_insecure_registries: "https://docker.m.daocloud.io"
# docker_default_runtime:

# Kubernetes
kube_version: 1.23.0

#High Availability and Load-Balancing
kubevip: false
vip: ""
vip_interface: ""

# 1.8.x feature: --feature-gates SelfHosting=true
init_opts: ""

# Any other additional opts you want to add..
#kubeadm_opts: "--control-plane-endpoint "
kubeadm_opts: ""
# For example:
# kubeadm_opts: '--apiserver-cert-extra-sans "k8s.domain.com,kubernetes.domain.com"'

service_cidr: "10.96.0.0/12"
pod_network_cidr: "10.244.0.0/16"

# Network implementation('flannel', 'calico', 'canal')
network: flannel

# Change this to an appropriate interface, preferably a private network.
# For example, on DigitalOcean, you would use eth1 as that is the default private network interface.
network_interface: "eth0"

#systemd_dir: /lib/systemd/system
#system_env_dir: /etc/sysconfig
network_dir: /etc/kubernetes/network
kubeadmin_config: /etc/kubernetes/admin.conf
kube_addon_dir: /etc/kubernetes/addon

# temporary directory used by additional features
tmp_dir: /tmp/kubeadm-ansible-files

# Additional feature to install
additional_features:
  helm: false
  crictl: false

# helm version
helm_version: v3.14.3

# crictl version
crictl_version: v1.30.0