---
# Fact os vars

- name: Get os_version from /etc/os-release
  when: os_version is not defined
  raw: "grep '^VERSION_ID=' /etc/os-release | sed s'/VERSION_ID=//' | sed s'/\"//g' | tr -d '\n'"
  register: os_version
  changed_when: False

- name: Get version_codename from /etc/os-release
  when: os_version is not defined
  raw: "grep '^VERSION_CODENAME=' /etc/os-release | sed s'/VERSION_CODENAME=//' | sed s'/\"//g' | tr -d '\n'"
  register: version_codename
  changed_when: False

- name: Get os_arch from /etc/os-release
  when: os_arch is not defined
  raw: "arch | tr -d '\n'"
  register: os_arch
  changed_when: False

- name: Get distro name from /etc/os-release
  when: os_distro is not defined
  raw: "grep '^NAME=' /etc/os-release | sed s'/NAME=//'"
  register: distro
  changed_when: False

- name: Set fact os_distro var to Debian
  when:
    - os_distro is not defined
    - "'Debian' in distro.stdout"
  set_fact:
    os_distro: Debian

- name: Set fact os_distro var to Debian
  when:
    - os_distro is not defined
    - "'Ubuntu' in distro.stdout"
  set_fact:
    os_distro: Debian

- name: Set fact os_distro var to RedHat
  when:
    - os_distro is not defined
    - "'CentOS' in distro.stdout"
  set_fact:
    os_distro: RedHat

- name: Override config file directory for Debian
  when: os_distro == "Debian"
  set_fact:
    system_env_dir: "/etc/default"
