---
- name: Install Containerd engine
  include_tasks: pkg.yml

- name: Create Containerd config directory
  when: container_runtime == "containerd"
  file:
    path: "/etc/containerd/certs.d"
    state: directory

- name: Copy Containerd environment config file
  when: container_runtime == "containerd"
  register: change_containerd
  template:
    src: "config.toml.j2"
    dest: "/etc/containerd/config.toml"

- name: Extract registry domain
  when: containerd_registry_mirrors is defined and containerd_registry_mirrors | length > 0
  set_fact:
    registry_domain: "{{ containerd_registry_mirrors | regex_replace('^https?://([^/]+).*', '\\1') }}"

- name: Create Containerd config directory
  when: registry_domain is defined and registry_domain | length > 0
  file:
    path: "/etc/containerd/certs.d/{{ registry_domain }}"
    state: directory

- name: Write hosts.toml
  when: registry_domain is defined and registry_domain | length > 0
  copy:
    dest: "/etc/containerd/certs.d/{{ registry_domain }}/hosts.toml"
    content: |
      server = "{{ containerd_registry_mirrors }}"
      
      [host."{{ containerd_registry_mirrors }}"]
        capabilities = ["pull", "resolve", "push"]
        skip_verify = true

- name: Enable and check Containerd service
  systemd:
    name: containerd
    daemon_reload: yes
    state: restarted
    enabled: yes
  register: started_containerd
