---
- name: Install apt-transport-https
  when: os_distro == "Debian"
  apt:
    name: 
      - "apt-transport-https"
      - "ca-certificates"
      - "curl"
      - "software-properties-common"
    state: present
    update_cache: true

- name: Add Docker APT GPG key
  when: os_distro == "Debian"
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg

- name: Add Docker APT repository
  when: os_distro == "Debian"
  apt_repository:
    repo: deb [arch={{ debian_arch.stdout | trim }}] https://mirrors.tuna.tsinghua.edu.cn/docker-ce/linux/ubuntu  {{ version_codename.stdout }} stable
    state: present
    filename: "docker"

- name: Add Docker yum repository
  when: os_distro == "RedHat"
  yum_repository:
    name: Docker
    description: Docker Repository
    file: docker
    baseurl: https://mirrors.aliyun.com/docker-ce/linux/centos/{{ os_version.stdout }}/{{ redhat_arch.stdout }}/stable/
    enabled: yes
    gpgcheck: yes
    gpgkey: https://download.docker.com/linux/centos/gpg

- name: Get Containerd version (Debian/Ubuntu)
  when:
    - debian_containerd_version is not defined
    - os_distro == "Debian"
  raw: "apt-cache madison containerd.io | awk '{print $3}' | grep -E '{{ containerd_version }}' | tr -d '\n'"
  register: debian_containerd_version
  changed_when: False

- name: Install Containerd engine (RHEL/CentOS)
  when: os_distro == "RedHat"
  yum:
    name: 
      - "containerd.io-{{ containerd_version }}"
    state: present

- name: Install Containerd engine (Debian/Ubuntu)
  when: os_distro == "Debian"
  apt:
    update_cache: true
    name:
      - "containerd.io={{ debian_containerd_version.stdout | trim }}"
    state: present
