---
- name: "Create tmp directory"
  file:
    path: "{{ tmp_dir }}"
    state: directory
    mode: 0755
  tags: helm

- name: "Check if Helm is installed"
  shell: command -v helm >/dev/null 2>&1
  register: helm_exists
  ignore_errors: yes
  tags: helm

- name: "Install Helm"
  block:
    - name: "Get Helm installer"
      get_url:
        url: https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
        dest: "{{ tmp_dir }}/get_helm.sh"
        mode: 0755

    - name: "Run the installer"
      environment:
          DESIRED_VERSION: "{{ helm_version }}"
      shell: "{{ tmp_dir }}/get_helm.sh --version {{ helm_version }}"

  when: helm_exists.rc != 0
  tags: helm

- name: "Clean-up"
  file:
    path: "{{ tmp_dir }}"
    state: absent
  ignore_errors: yes
  tags: helm
