---
- hosts: kube-cluster
  gather_facts: no
  become: yes
  roles:
    - { role: docker, tags: docker }
    - { role: kubernetes/install, tags: kubernetes }

- hosts: master[0]
  gather_facts: no
  become: yes
  roles:
    - { role: kube-vip, tags: kube-vip }

- hosts: master[0]
  gather_facts: no
  become: yes
  tasks:
  roles:
    - { role: kubernetes/master, tags: master }
    - { role: cni, tags: cni }

- hosts: master:!master[0]
  gather_facts: no
  become: yes
  roles:
    - { role: kubernetes/master-backup, tags: master-backup }

- hosts: node
  gather_facts: no
  become: yes
  roles:
    - { role: kubernetes/node, tags: node }

- hosts: master
  gather_facts: no
  become: yes
  tasks:
    - name: "Helm role"
      include_role:
        name: helm
      when: "additional_features.helm"
      run_once: yes
      tags: helm

    - name: "MetalLB role"
      include_role:
        name: metallb
      when: "additional_features.metallb"
      run_once: yes
      tags: metallb

    - name: "Healthcheck role"
      include_role:
        name: healthcheck
      when: "additional_features.healthcheck"
      run_once: yes
      tags: healthcheck

