---
- hosts: kube-cluster
  gather_facts: yes
  become: yes
  roles:
    - { role: docker, tags: docker }
    - { role: kubernetes/install, tags: kubernetes }

- hosts: master
  gather_facts: yes
  become: yes
  tasks:
    - name: "kube-vip role"
      include_role:
        name: kube-vip
      when: "kube_vip is defined and kube_vip > 0"
      run_once: yes
      tags: kube-vip

- hosts: master
  gather_facts: yes
  become: yes
  tasks:
    - name: "master role"
      include_role:
        name: kubernetes/master
      run_once: yes
      tags: master
    - name: "cni role"
      include_role:
        name: cni
      run_once: yes
      tags: cni

- hosts: master:!master[0]
  gather_facts: yes
  become: yes
  tasks:
    - name: "master-backup role"
      include_role:
        name: kubernetes/master-backup
      when: 
        - "kube_vip is defined and kube_vip > 0"
        - "groups['master'] | length > 2"
      tags: master-backup

- hosts: node
  gather_facts: yes
  become: yes
  tasks:
    - name: "node role"
      include_role:
        name: kubernetes/node
      tags: node

- hosts: master
  gather_facts: yes
  become: yes
  tasks:
    - name: "Helm role"
      include_role:
        name: helm
      when: "additional_features.helm"
      run_once: yes
      tags: helm

    - name: "MetalLB role"
      include_role:
        name: metallb
      when: "additional_features.metallb"
      run_once: yes
      tags: metallb

    - name: "Healthcheck role"
      include_role:
        name: healthcheck
      when: "additional_features.healthcheck"
      run_once: yes
      tags: healthcheck

