---
- hosts: kube-cluster
  gather_facts: no
  become: yes
  tasks:
    - name: "containerd role"
      include_role:
        name: container-runtime/containerd
      when: container_runtime == "containerd" or container_runtime == "docker" 
      tags: containerd

    - name: "docker role"
      include_role:
        name: container-runtime/docker
      when: container_runtime == "docker" 
      tags: docker

- hosts: kube-cluster
  gather_facts: no
  become: yes
  roles:
    - { role: kubernetes/install, tags: kubernetes }

- hosts: master
  gather_facts: no
  become: yes
  tasks:
    - name: "kube-vip role"
      include_role:
        name: kube-vip
      when: "kubevip"
      run_once: yes
      tags: kube-vip

- hosts: master[0]
  gather_facts: no
  become: yes
  tasks:
  roles:
    - { role: kubernetes/master, tags: master }
    - { role: cni, tags: cni }

- hosts: master:!master[0]
  gather_facts: no
  become: yes
  roles:
    - { role: kubernetes/master-backup, tags: master-backup }

- hosts: node
  gather_facts: no
  become: yes
  roles:
    - { role: kubernetes/node, tags: node }

- hosts: master
  gather_facts: no
  become: yes
  tasks:
    - name: "Helm role"
      include_role:
        name: helm
      when: "additional_features.helm"
      run_once: yes
      tags: helm


