---

- name: Add Kubernetes APT GPG key
  when: os_distro == "Debian"
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present

- name: Add Kubernetes APT repository
  when: os_distro == "Debian"
  apt_repository:
    repo: deb https://mirrors.tuna.tsinghua.edu.cn/kubernetes/apt kubernetes-xenial main
    state: present
    filename: 'kubernetes'

- name: Add Kubernetes yum repository
  when: os_distro == "RedHat"
  yum_repository:
    name: Kubernetes
    description: Kubernetes Repository
    file: kubernetes
    baseurl: http://mirrors.tuna.tsinghua.edu.cn/kubernetes/yum/repos/kubernetes-el7-{{ os_arch.stdout }}
    enabled: yes
    gpgcheck: no

- name: Install kubernetes packages (RHEL/CentOS)
  when: os_distro == "RedHat"
  yum:
    name: "{{ pkgs }}"
    update_cache: yes
    state: present
  with_items: "{{ pkgs }}"

- name: Install kubernetes packages (Debian/Ubuntu)
  when: os_distro == "Debian"
  apt:
    name: "{{ pkgs }}"
    update_cache: yes
    state: present
  with_items: "{{ pkgs }}"
