---

- name: Add Kubernetes APT GPG key
  when: os_distro == "Debian"
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present

- name: Add Kubernetes APT repository
  when: os_distro == "Debian"
  apt_repository:
    repo: deb https://mirrors.tuna.tsinghua.edu.cn/kubernetes/apt kubernetes-xenial main
    state: present
    filename: 'kubernetes'

- name: Add Kubernetes yum repository
  when: os_distro == "RedHat"
  yum_repository:
    name: Kubernetes
    description: Kubernetes Repository
    file: kubernetes
    baseurl: http://mirrors.tuna.tsinghua.edu.cn/kubernetes/yum/repos/kubernetes-el7-{{ redhat_arch.stdout }}
    enabled: yes
    gpgcheck: no

- name: Install kubernetes packages (RHEL/CentOS)
  when: os_distro == "RedHat"
  yum:
    name:
      - "kubelet-{{ kube_version }}"
      - "kubeadm-{{ kube_version }}"
      - "kubectl-{{ kube_version }}"
    update_cache: yes
    state: present

- name: Get kubernetes version (Debian/Ubuntu)
  when:
    - debian_docker_version is not defined
    - os_distro == "Debian"
  raw: "apt-cache madison kubelet | awk '{print $3}' | grep -E '{{ kube_version }}' | tr -d '\n'"
  register: debian_kube_version
  changed_when: False

- name: Install kubernetes packages (Debian/Ubuntu)
  when: os_distro == "Debian"
  apt:
    name:
      - "kubelet={{ debian_kube_version.stdout }}"
      - "kubeadm={{ debian_kube_version.stdout }}"
      - "kubectl={{ debian_kube_version.stdout }}"
    update_cache: yes
    state: present
