---

- name: Check if control plane haproxy has already run
  stat:
    path: "/etc/kubernetes/manifests/kube-vip.yaml"
  register: kubeadm_ha

- name: Create control plane haproxy if needed
  include_tasks: pkg.yml
  when: 
    - not kubeadm_ha.stat.exists
    - kube_vip is defined and kube_vip > 0
  run_once: yes
