---
- name: Install apt-transport-https
  when: os_distro == "Debian"
  apt:
    name: "apt-transport-https"
    state: present
    update_cache: yes

- name: Add Docker APT GPG key
  when: os_distro == "Debian"
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg

- name: Add Docker APT repository
  when: os_distro == "Debian"
  apt_repository:
    repo: deb [arch={{ debian_arch.stdout }}] https://mirrors.tuna.tsinghua.edu.cn/docker-ce/linux/ubuntu  {{ version_codename.stdout }} stable
    state: present
    filename: "docker"

- name: Add Docker yum repository
  when: os_distro == "RedHat"
  yum_repository:
    name: Docker
    description: Docker Repository
    file: docker
    baseurl: https://mirrors.tuna.tsinghua.edu.cn/docker-ce/linux/centos/{{ os_version.stdout }}/{{ redhat_arch.stdout }}/stable/
    enabled: yes
    gpgcheck: yes
    gpgkey: https://download.docker.com/linux/centos/gpg

- name: Install docker engine (RHEL/CentOS)
  when: os_distro == "RedHat"
  yum:
    name: 
      - "docker-ce-{{ docker_version }}"
      - "docker-ce-cli-{{ docker_version }}"
      - "containerd.io"
    state: present

- name: Get docker engine version (Debian/Ubuntu)
  when:
    - debian_docker_version is not defined
    - os_distro == "Debian"
  raw: "apt-cache madison docker-ce | awk '{print $3}' | grep -E '{{ docker_version }}' | tr -d '\n'"
  register: debian_docker_version
  changed_when: False

- name: Install docker engine (Debian/Ubuntu)
  when: os_distro == "Debian"
  apt:
    update_cache: yes
    name:       
      - "docker-ce={{ debian_docker_version.stdout }}"
      - "docker-ce-cli={{ debian_docker_version.stdout }}"
      - "containerd.io"
    state: present

- name: Hold docker version
  when: os_distro == "Debian"
  dpkg_selections:
    name: docker-ce
    selection: hold
